version: '3.8'

services:
  # Orthanc PACS Server
  orthanc:
    image: orthancteam/orthanc:latest
    container_name: orthanc-server
    ports:
      - "8042:8042"  # HTTP port
      - "4242:4242"  # DICOM port
    volumes:
      - ../orthanc-mwl/config/orthanc-minimal.json:/etc/orthanc/orthanc.json:ro
      - ../orthanc-mwl/worklists:/worklists:ro
      - orthanc-db:/var/lib/orthanc/db
      - orthanc-cache:/var/lib/orthanc/WebViewerCache
    environment:
      - ORTHANC_NAME=ORTHANC
      - VERBOSE_ENABLED=true
    networks:
      - pacs-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8042/app/explorer.html"]
      interval: 30s
      timeout: 10s
      retries: 3

  # DCMTK FindSCU Client
  dcmtk-findscu:
    build: .
    container_name: dcmtk-findscu-client
    depends_on:
      - orthanc
    env_file:
      - .env
    volumes:
      - ./scripts:/usr/local/bin:ro
      - ./logs:/var/log/findscu
      - ./results:/opt/findscu/results
    networks:
      - pacs-network
    restart: unless-stopped
    command: tail -f /dev/null  # Keep container running

  # Hasta Radiologi API (optional - if you want it in same stack)
  hasta-radiologi-api:
    build: 
      context: ../hasta_radiologi
      dockerfile: Dockerfile
    container_name: hasta-radiologi-api
    ports:
      - "3000:3000"
    depends_on:
      - orthanc
      - dcmtk-findscu
    environment:
      - NODE_ENV=production
      - PACS_HOST=orthanc
      - PACS_PORT=4242
      - FINDSCU_CONTAINER=dcmtk-findscu-client
    volumes:
      - ../hasta_radiologi:/app
      - ../orthanc-mwl/worklists:/app/worklists:ro
    networks:
      - pacs-network
    restart: unless-stopped

volumes:
  orthanc-db:
  orthanc-cache:

networks:
  pacs-network:
    driver: bridge
