services:
  # Simple Orthanc PACS Server (with plugins)
  orthanc:
    image: jodogne/orthanc-plugins:latest
    container_name: orthanc-server
    ports:
      - "8042:8042"  # HTTP port
      - "4242:4242"  # DICOM port
    volumes:
      - ../orthanc-mwl/config/orthanc-plugins.json:/etc/orthanc/orthanc.json:ro
      - ../orthanc-mwl/worklists:/worklists:ro
      - orthanc-db:/var/lib/orthanc/db
    environment:
      - ORTHANC__NAME=ORTHANC
      - ORTHANC__DICOM_AET=ORTHANC
      - ORTHANC__DICOM_PORT=4242
      - ORTHANC__HTTP_PORT=8042
    networks:
      - pacs-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8042/app/explorer.html"]
      interval: 30s
      timeout: 10s
      retries: 3

  # DCMTK FindSCU Client
  dcmtk-findscu:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: dcmtk-findscu-client
    depends_on:
      - orthanc
    env_file:
      - .env
    volumes:
      - ./scripts:/usr/local/bin:ro
      - ./logs:/var/log/findscu
      - ./results:/opt/findscu/results
    networks:
      - pacs-network
    restart: unless-stopped
    command: tail -f /dev/null  # Keep container running

volumes:
  orthanc-db:

networks:
  pacs-network:
    driver: bridge
